name: Deploy to GCP

on:
  push:
    branches-ignore:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Write Google Creds to JSON file'
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > credentials.json

      - name: 'Terraform init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
          TF_VAR_SQUARE_WEBHOOK_SIGNATURE_KEY: ${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}

      - name: 'Terraform plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
          TF_VAR_SQUARE_WEBHOOK_SIGNATURE_KEY: ${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}
