name: Deploy to GCP

on:
  push:
    branches-ignore:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Extract Service Account Credentials'
        id: write_file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'serviceaccount.json'
          encodedString: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - run: |
        cat ${{ steps.write_file.outputs.filePath }}

      - name: 'Terraform init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.write_file.outputs.filePath }}
          TF_VAR_SQUARE_WEBHOOK_SIGNATURE_KEY: ${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}

      - name: 'Terraform plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.write_file.outputs.filePath }}
          TF_VAR_SQUARE_WEBHOOK_SIGNATURE_KEY: ${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}

      - name: 'Terraform apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.write_file.outputs.filePath }}
          TF_VAR_SQUARE_WEBHOOK_SIGNATURE_KEY: ${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}
