name: Deploy to GCP

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up gcloud SDK
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: components update

      - name: Export environment variables to yaml file
        env:
          SQUARE_WEBHOOK_SIGNATURE_KEY: ${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}
        run: |
          echo "SQUARE_WEBHOOK_SIGNATURE_KEY: ${SQUARE_WEBHOOK_SIGNATURE_KEY}" > .env.yaml

      - name: Ensure topic exists for pubsub
        id: topicList
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: pubsub topics list --filter=name:projects/${{ secrets.GCLOUD_PROJECT_ID }}/topics/orders --format="value(name)" > /tmp/val

      - name: Export topic (if found)
        shell: bash
        run: echo "##[set-output name=topic;]$(cat /tmp/val)"
        id: topic_export

      - name: Create topic for pubsub
        # step only runs if output from topicList was blank
        if: steps.topic_export.outputs.topic != 'projects/${{ secrets.GCLOUD_PROJECT_ID }}/topics/orders'
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: pubsub topics create projects/${{ secrets.GCLOUD_PROJECT_ID }}/topics/orders

      - name: Deploy function with an HTTP trigger
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: functions deploy handle_webhook --env-vars-file .env.yaml --runtime python37 --trigger-http --allow-unauthenticated --memory=128MB
